baseURL: "https://darshandeshmukh11.github.io/"
languageCode: "en-us"
title: "Darshan Deshmukh"
theme: "PaperMod"
pagination:
  pagerSize: 5


params:
  profileMode:
    enabled: false

  defaultTheme: dark

  homeInfoContent: markdown

  homeInfoParams:
    Title: "Hi, I am Darshan Deshmukh"
    Content: |
      Welcome to my personal website.  
      I'm passionate about DevOps, Cloud, Automation.

  socialIcons:
    - name: github
      url: "https://github.com/darshandeshmukh11"
    - name: linkedin
      url: "https://linkedin.com/in/darshandeshmukh"
    - name: email
      url: "mailto:darshandeshmukh11@gmail.com"

menu:
  main:
    - identifier: blog
      name: Blog
      url: /posts/
      weight: 10

